const products=JSON.parse(localStorage.bv_products||JSON.stringify([
{id:1,name:"X-Bacon",price:24.9,emoji:"🍔",desc:"Hambúrguer, queijo e bacon."},
{id:2,name:"X-Tudo",price:28.9,emoji:"🍔",desc:"Completo e caprichado."},
{id:3,name:"Cheddar Bacon",price:26.9,emoji:"🍔",desc:"Cheddar cremoso e bacon."},
{id:4,name:"Smash Burger",price:29.9,emoji:"🍔",desc:"Duas carnes smash e queijo."},
{id:5,name:"Batata P",price:12,emoji:"🍟",desc:"Crocante e sequinha."},
{id:6,name:"Coca-Cola",price:6,emoji:"🥤",desc:"350ml gelada."}]));
let cart=[],delivery=true,payment="Pix",orders=JSON.parse(localStorage.bv_orders||"[]"),config=JSON.parse(localStorage.bv_config||'{"fee":5,"wa":"5500000000000"}');
const brl=n=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const $=id=>document.getElementById(id);
function go(id){$(id).scrollIntoView({behavior:"smooth"})}
function renderProducts(){$("products").innerHTML=products.map(p=>`<article class="product"><div class="photo">${p.emoji}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="price">${brl(p.price)}</div><button class="add" onclick="add(${p.id})">Adicionar</button></article>`).join("");renderManage()}
function add(id){let p=products.find(x=>x.id===id),i=cart.find(x=>x.id===id);i?i.q++:cart.push({...p,q:1});renderCart()}
function change(id,d){let i=cart.find(x=>x.id===id);i.q+=d;if(i.q<1)cart=cart.filter(x=>x.id!==id);renderCart()}
function couponValue(sub){let c=$("coupon").value.trim().toUpperCase();return c==="BV10"?sub*.1:c==="PRIMEIRA"?5:0}
function renderCart(){let sub=cart.reduce((s,x)=>s+x.price*x.q,0),fee=delivery&&sub?+config.fee:0,disc=couponValue(sub),total=Math.max(0,sub+fee-disc);$("cart").innerHTML=cart.length?cart.map(x=>`<div class="line"><span>${x.q}x ${x.name}<br><small class="mini"><button onclick="change(${x.id},-1)">−</button> <button onclick="change(${x.id},1)">+</button></small></span><b>${brl(x.price*x.q)}</b></div>`).join(""):'<p class="muted">Carrinho vazio.</p>';$("sub").textContent=brl(sub);$("fee").textContent=brl(fee-disc);$("total").textContent=brl(total);$("count").textContent=cart.reduce((s,x)=>s+x.q,0)}
function mode(m,b){delivery=m==="entrega";document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("address").style.display=delivery?"block":"none";renderCart()}
function pay(p,b){payment=p;document.querySelectorAll(".pay button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("troco").classList.toggle("hide",p!=="Dinheiro")}
function finish(){if(!cart.length)return toast("Adicione um produto.");if(delivery&&(!$("name").value||!$("street").value||!$("num").value||!$("bairro").value))return toast("Preencha nome e endereço.");let sub=cart.reduce((s,x)=>s+x.price*x.q,0),fee=delivery?+config.fee:0,disc=couponValue(sub),total=Math.max(0,sub+fee-disc);let id=Date.now().toString().slice(-5);let o={id,customer:$("name").value||"Cliente",items:cart.map(x=>`${x.q}x ${x.name}`).join(", "),total,payment,status:"Novo",time:new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})};orders.unshift(o);localStorage.bv_orders=JSON.stringify(orders);renderAdmin();let msg=`🍔 *BV LANCHES — PEDIDO #${id}*%0A${o.items}%0A%0A*Total:* ${brl(total)}%0A*Pagamento:* ${payment}%0A`;if(delivery)msg+=`%0A📍 ${$("street").value}, ${$("num").value} — ${$("bairro").value}%0A${$("comp").value}`;if(payment==="Dinheiro")msg+=`%0A💵 Troco para: ${$("troco").value||"não informado"}`;window.open(`https://wa.me/${config.wa}?text=${msg}`,"_blank");toast("Pedido criado!");cart=[];renderCart()}
function renderAdmin(){let rev=orders.reduce((s,o)=>s+o.total,0);$("sOrders").textContent=orders.length;$("sRevenue").textContent=brl(rev);$("sAvg").textContent=brl(orders.length?rev/orders.length:0);$("sNew").textContent=orders.filter(o=>o.status==="Novo").length;$("orders").innerHTML=orders.length?orders.map(o=>`<div class="order"><div class="line"><b>#${o.id} — ${o.customer}</b><span class="status">${o.status}</span></div><p>${o.items}</p><div class="mini">${brl(o.total)} · ${o.payment} · ${o.time}</div><select onchange="statusOrder('${o.id}',this.value)"><option ${o.status==="Novo"?"selected":""}>Novo</option><option ${o.status==="Confirmado"?"selected":""}>Confirmado</option><option ${o.status==="Em preparo"?"selected":""}>Em preparo</option><option ${o.status==="Pronto"?"selected":""}>Pronto</option><option ${o.status==="Saiu para entrega"?"selected":""}>Saiu para entrega</option><option ${o.status==="Entregue"?"selected":""}>Entregue</option><option ${o.status==="Cancelado"?"selected":""}>Cancelado</option></select></div>`).join(""):'<p class="muted">Nenhum pedido.</p>'}
function statusOrder(id,s){let o=orders.find(x=>x.id===id);if(o){o.status=s;localStorage.bv_orders=JSON.stringify(orders);renderAdmin();toast("Status atualizado")}}
function renderManage(){$("manage").innerHTML=products.map((p,i)=>`<div class="manageRow"><span>${p.emoji} ${p.name} — ${brl(p.price)}</span><button onclick="removeProduct(${i})">Excluir</button></div>`).join("")}
function addProduct(){let n=prompt("Nome do produto:");if(!n)return;let v=parseFloat(prompt("Preço:","20"));if(!v)return;products.push({id:Date.now(),name:n,price:v,emoji:"🍔",desc:"Novo produto"});localStorage.bv_products=JSON.stringify(products);renderProducts()}
function removeProduct(i){if(confirm("Excluir este produto?")){products.splice(i,1);localStorage.bv_products=JSON.stringify(products);renderProducts()}}
function saveCfg(){config.fee=parseFloat($("feeCfg").value)||0;config.wa=$("waCfg").value.replace(/\D/g,"");localStorage.bv_config=JSON.stringify(config);toast("Configurações salvas")}
function demoOrder(){orders.unshift({id:Date.now().toString().slice(-5),customer:"Cliente Demo",items:"1x X-Bacon, 1x Batata P",total:36.9,payment:"Pix",status:"Novo",time:new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}));localStorage.bv_orders=JSON.stringify(orders);renderAdmin();toast("🔔 Novo pedido recebido")}
function toast(t){$("toast").textContent=t;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2500)}
function login(){if($("email").value==="admin@bvlanche.com"&&$("pass").value==="123456"){sessionStorage.bv="1";$("login").style.display="none"}else $("err").textContent="E-mail ou senha incorretos."}
function logout(){sessionStorage.removeItem("bv");$("login").style.display="flex"}
if(sessionStorage.bv==="1")$("login").style.display="none";
$("coupon").addEventListener("input",renderCart);$("feeCfg").value=config.fee;$("waCfg").value=config.wa;
renderProducts();renderCart();renderAdmin();
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
