const $=id=>document.getElementById(id),brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function safeParse(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch(e){localStorage.removeItem(k);return f}}
const defaultProducts=[{id:1,name:'X-Salada',price:12.99,emoji:'🍔',desc:'Pão, ovo, mussarela, requeijão, presunto e salada.',category:'Lanches'},{id:2,name:'Hambúrguer',price:15,emoji:'🍔',desc:'Pão, bife, presunto, mussarela, milho e requeijão.',category:'Lanches'},{id:3,name:'X-Egg',price:17,emoji:'🍔',desc:'Pão, bife, presunto, mussarela, ovo, milho, batata e salada.',category:'Lanches'},{id:4,name:'X-Bacon',price:19,emoji:'🍔',desc:'Pão, bife, bacon, requeijão, presunto, cheddar, mussarela, batata, milho e salada.',category:'Lanches'},{id:5,name:'BV X-Tudão',price:23,emoji:'🍔',desc:'Pão, 2 bifes, presunto, mussarela, calabresa, requeijão, milho e salada.',category:'Lanches'},{id:6,name:'X-Explosão',price:27,emoji:'🍔',desc:'Pão, bife, ovo, presunto, mussarela, calabresa, requeijão, batata, milho, cebola, alface e tomate.',category:'Lanches'},{id:7,name:'X-Caminhoneiro',price:28,emoji:'🍔',desc:'Pão, 2 bifes, ovo, presunto, mussarela, bacon, cheddar, requeijão e salada.',category:'Lanches'},{id:8,name:'BV-Megã Monstrão',price:34,emoji:'🍔',desc:'Pão, 4 bifes, 2 ovos, calabresa, bacon, cheddar, requeijão, frango desfiado, batata e salada.',category:'Lanches'}];
let products=safeParse('bv_products',null);if(!Array.isArray(products)){products=defaultProducts;localStorage.bv_products=JSON.stringify(products)}
let cart=safeParse('bv_cart',[]),orders=safeParse('bv_orders',[]),config=safeParse('bv_config',{fee:5,wa:'5531984595968',bairroFees:{}}),saved=safeParse('bv_saved_address',null);if(!Array.isArray(cart))cart=[];if(!Array.isArray(orders))orders=[];if(!config||typeof config!=='object')config={fee:5,wa:'5531984595968',bairroFees:{}};if(!config.bairroFees||typeof config.bairroFees!=='object')config.bairroFees={};
const usersDefault=[{id:'admin-marco',name:'Administrador',email:'admin@bvlanches.com',pass:'BV123456',role:'administrador'},{id:'user-demo',name:'Usuário',email:'cliente@bvlanches.com',pass:'BV123456',role:'usuario'}];function users(){let u=safeParse('bv_users',null);if(!Array.isArray(u))u=[];let changed=false;usersDefault.forEach(d=>{const i=u.findIndex(x=>String(x.email||'').trim().toLowerCase()===d.email);if(i<0){u.push({...d});changed=true}else{if(!u[i].id){u[i].id=d.id;changed=true}if(!u[i].role){u[i].role=d.role;changed=true}}});if(changed||!localStorage.getItem('bv_users'))localStorage.bv_users=JSON.stringify(u);return u}function role(){return sessionStorage.getItem('bv_role')||''}function admin(){return role()==='administrador'}function moto(){return role()==='motoboy'}
const pages={inicio:'Início',cardapio:'Cardápio',pedido:'Meu pedido',acompanhar:'Acompanhar pedido',dashboard:'Dashboard',pedidos:'Pedidos',produtos:'Produtos',cupons:'Cupons',config:'Configurações'},publicPages=['inicio','cardapio','pedido','acompanhar'];
function toast(t){const x=$('toast');if(x){x.textContent=t;x.style.display='block';clearTimeout(window._toast);window._toast=setTimeout(()=>x.style.display='none',2200)}}
function applyAccess(){document.querySelectorAll('.adminOnly').forEach(x=>x.style.display=admin()?'':'none');document.querySelectorAll('.adminHide').forEach(x=>x.style.display=admin()?'none':'');document.querySelectorAll('[data-role="motoboyOnly"]').forEach(x=>x.style.display=moto()&&!admin()?'':'none');const q=$('adminQuick');if(q)q.style.display=admin()?'':'none'}
function allowed(p){return admin()||publicPages.includes(p)||(moto()&&p==='pedidos')}
function showPage(p){if(!pages[p])p='inicio';if(!allowed(p)){toast('Você não tem permissão para acessar esta tela.');return false}localStorage.bv_page=p;document.querySelectorAll('.page').forEach(x=>x.classList.remove('activePage'));const x=$('page-'+p);if(x)x.classList.add('activePage');document.querySelectorAll('.sideNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if($('pageTitle'))$('pageTitle').textContent=pages[p];if($('sidebar'))$('sidebar').classList.remove('open');try{if(p==='cardapio')renderProducts();if(p==='pedido')renderCart();if(p==='produtos')renderManage();if(admin()||moto())renderAdmin();if(p==='config'){renderUsers();renderBairroFees()};if(p==='acompanhar')renderTracking()}catch(e){console.error('BV tela:',e)}return true}
function toggleSidebar(){if($('sidebar'))$('sidebar').classList.toggle('open')}function closeLogin(){if($('login'))$('login').style.display='none';if($('err'))$('err').textContent=''}function openAdmin(p='dashboard'){if(admin()||(moto()&&p==='pedidos'))showPage(p);else{if($('login'))$('login').style.display='flex';if($('email'))$('email').focus()}}
function login(){const e=String($('email')?.value||'').trim().toLowerCase(),p=String($('pass')?.value||'').trim(),list=users(),u=list.find(x=>String(x.email||'').trim().toLowerCase()===e&&String(x.pass??'').trim()===p);if(!e||!p){if($('err'))$('err').textContent='Digite o e-mail e a senha.';return}if(!u){if($('err'))$('err').textContent='E-mail ou senha incorretos. Use os dados exibidos abaixo.';return}sessionStorage.setItem('bv_user_id',u.id);sessionStorage.setItem('bv_role',u.role||'usuario');sessionStorage.setItem('bv',u.role==='administrador'?'1':'0');if($('login'))$('login').style.display='none';if($('err'))$('err').textContent='';applyAccess();showPage(u.role==='administrador'?'dashboard':u.role==='motoboy'?'pedidos':'inicio');toast('Login realizado com sucesso!')}
function logout(){sessionStorage.clear();localStorage.bv_page='inicio';if($('login'))$('login').style.display='flex';if($('email'))$('email').value='';if($('pass'))$('pass').value='';applyAccess();showPage('inicio');toast('Conta desconectada')}
function openRegister(){const m=$('registerModal');if(!m)return;m.classList.add('show');m.setAttribute('aria-hidden','false');$('registerErr').textContent='';$('registerName')?.focus()}
function closeRegister(){const m=$('registerModal');if(!m)return;m.classList.remove('show');m.setAttribute('aria-hidden','true')}
function registerUser(e){if(e)e.preventDefault();const name=$('registerName')?.value.trim()||'',email=$('registerEmail')?.value.trim().toLowerCase()||'',pass=$('registerPass')?.value||'',pass2=$('registerPass2')?.value||'',err=$('registerErr');if(err)err.textContent='';if(!name||!email||!pass||!pass2){if(err)err.textContent='Preencha todos os campos.';return}if(pass.length<6){if(err)err.textContent='A senha deve ter pelo menos 6 caracteres.';return}if(pass!==pass2){if(err)err.textContent='As senhas não coincidem.';return}const list=users();if(list.some(u=>String(u.email).toLowerCase()===email)){if(err)err.textContent='Este e-mail já está cadastrado.';return}const u={id:'user-'+Date.now(),name,email,pass,role:'usuario'};list.push(u);localStorage.bv_users=JSON.stringify(list);$('email').value=email;$('pass').value='';$('registerName').value='';$('registerEmail').value='';$('registerPass').value='';$('registerPass2').value='';closeRegister();if($('err'))$('err').textContent='Conta criada! Digite sua senha para entrar.';toast('Conta criada como usuário comum.')}
function renderProducts(){const box=$('products');if(box)box.innerHTML=products.map(p=>`<article class="product"><div class="photo">${p.emoji||'🍔'}</div><span class="categoryBadge">${p.category||'Lanches'}</span><h3>${p.name}</h3><p>${p.desc||''}</p><div class="price">${brl(p.price)}</div><button class="add" onclick="add(${p.id})">Adicionar</button></article>`).join('');renderManage()}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;const i=cart.find(x=>x.id===id);i?i.q++:cart.push({...p,q:1});localStorage.bv_cart=JSON.stringify(cart);renderCart();toast('Produto adicionado')}
function change(id,d){const x=cart.find(x=>x.id===id);if(!x)return;x.q+=d;if(x.q<1)cart=cart.filter(y=>y.id!==id);localStorage.bv_cart=JSON.stringify(cart);renderCart()}
function fee(){const b=$('bairro')?.value.trim().toLowerCase();if(b&&config.bairroFees[b]!=null)return Number(config.bairroFees[b])||0;return Number(config.fee)||0}function subtotal(){return cart.reduce((s,x)=>s+(Number(x.price)||0)*(Number(x.q)||0),0)}
function renderCart(){const sub=subtotal(),f=$('address')?.style.display!=='none'&&sub?fee():0,c=($('coupon')?.value||'').toUpperCase(),disc=c==='BV10'?sub*.1:c==='PRIMEIRA'?5:0,t=Math.max(0,sub+f-disc);if($('cart'))$('cart').innerHTML=cart.length?cart.map(x=>`<div class="line"><span>${x.q}x ${x.name}<br><small><button onclick="change(${x.id},-1)">−</button> <button onclick="change(${x.id},1)">+</button></small></span><b>${brl(x.price*x.q)}</b></div>`).join(''):'<p class="muted">Carrinho vazio.</p>';if($('sub'))$('sub').textContent=brl(sub);if($('fee'))$('fee').textContent=brl(f-disc);if($('total'))$('total').textContent=brl(t);['count','sideCount','quickCount'].forEach(id=>{if($(id))$(id).textContent=cart.reduce((s,x)=>s+x.q,0)})}
function mode(m,b){if($('address'))$('address').style.display=m==='entrega'?'block':'none';document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));if(b)b.classList.add('active');renderCart()}function pay(p,b){localStorage.bv_payment=p;document.querySelectorAll('.pay button').forEach(x=>x.classList.remove('active'));if(b)b.classList.add('active');if($('troco'))$('troco').classList.toggle('hide',p!=='Dinheiro')}
function finish(){if(!cart.length)return toast('Adicione um produto.');const delivery=$('address')?.style.display!=='none',payment=localStorage.bv_payment||'Pix';if(delivery&&(!$('name')?.value||!$('street')?.value||!$('num')?.value||!$('bairro')?.value))return toast('Preencha nome e endereço.');if(!delivery&&!$('name')?.value)return toast('Informe seu nome.');const sub=subtotal(),f=delivery?fee():0,c=($('coupon')?.value||'').toUpperCase(),disc=c==='BV10'?sub*.1:c==='PRIMEIRA'?5:0,total=Math.max(0,sub+f-disc),id=String(Date.now()).slice(-5),address=delivery?{rua:$('street').value,numero:$('num').value,bairro:$('bairro').value,cep:$('cep').value,complemento:$('comp').value}:null,o={id,customer:$('name').value,phone:$('phone').value,items:cart.map(x=>x.q+'x '+x.name).join(', '),total,payment,delivery:delivery?'Entrega':'Retirada',address,status:payment==='Pix'?'Aguardando pagamento':'Novo',paid:payment!=='Pix',time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})};orders.unshift(o);localStorage.bv_orders=JSON.stringify(orders);if(address){saved={name:o.customer,phone:o.phone,...address};localStorage.bv_saved_address=JSON.stringify(saved)};localStorage.bv_last_order=JSON.stringify({id:o.id,phone:o.phone});cart=[];localStorage.bv_cart='[]';if($('trackId'))$('trackId').value=id;if($('trackPhone'))$('trackPhone').value=o.phone;showPage('acompanhar');renderTracking(o);toast('Pedido criado com sucesso!')}
function renderAdmin(){const delivered=orders.filter(o=>o.status==='Entregue'),rev=delivered.reduce((s,o)=>s+(Number(o.total)||0),0),pending=orders.filter(o=>!['Entregue','Cancelado'].includes(o.status)).length;if($('sOrders'))$('sOrders').textContent=delivered.length;if($('sRevenue'))$('sRevenue').textContent=brl(rev);if($('sAvg'))$('sAvg').textContent=brl(delivered.length?rev/delivered.length:0);if($('sNew'))$('sNew').textContent=pending;if($('sideNew'))$('sideNew').textContent=pending;if($('dashNotice'))$('dashNotice').textContent=pending?'🔔 '+pending+' pedido(s) pendente(s).':'Nenhum pedido novo.';if($('dashboardOrders'))$('dashboardOrders').innerHTML=delivered.length?delivered.map(o=>`<div class="order"><div class="line"><b>#${o.id} — ${o.customer}</b><span class="status">Entregue</span></div><p>${o.items}</p><b>${brl(o.total)}</b></div>`).join(''):'<p class="muted">Nenhum pedido entregue ainda.</p>';if($('orders'))$('orders').innerHTML=orders.length?orders.map(o=>{const adr=o.address?`${o.address.rua}, ${o.address.numero} — ${o.address.bairro}`:'Retirada no local',opts=['Aguardando pagamento','Novo','Confirmado','Em preparo','Pronto','Saiu para entrega','Entregue','Cancelado'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('');return `<div class="order"><div class="line"><b>#${o.id} — ${o.customer}</b><span class="status">${o.status}</span></div><p><b>Itens:</b> ${o.items}</p><p>📍 ${adr}</p><p>💳 ${o.payment}${o.paid?' · Pago':''}</p><b>${brl(o.total)}</b>${o.payment==='Pix'&&!o.paid?`<button class="confirmPix" onclick="confirmPix('${o.id}')">✅ Confirmar pagamento Pix</button>`:''}<select onchange="statusOrder('${o.id}',this.value)">${opts}</select></div>`}).join(''):'<p class="muted">Nenhum pedido.</p>'}
function confirmPix(id){const o=orders.find(x=>x.id===id);if(!o)return;o.paid=true;o.status='Confirmado';o.paidAt=new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});localStorage.bv_orders=JSON.stringify(orders);renderAdmin();toast('Pix confirmado')}
function statusOrder(id,s){const o=orders.find(x=>x.id===id);if(!o)return;if(o.payment==='Pix'&&!o.paid&&s!=='Aguardando pagamento')return toast('Confirme o pagamento Pix primeiro.');o.status=s;localStorage.bv_orders=JSON.stringify(orders);renderAdmin();renderTracking();toast('Status atualizado')}
function renderTracking(o){if(!o){const l=safeParse('bv_last_order',null);o=l&&orders.find(x=>x.id===l.id&&x.phone===l.phone)}const r=$('trackingResult');if(!r)return;if(!o){r.innerHTML='<p class="muted">Digite os dados do pedido para consultar.</p>';return}const steps=['Novo','Confirmado','Em preparo','Pronto','Saiu para entrega','Entregue'],p=steps.indexOf(o.status);r.innerHTML=`<div class="trackHead"><div><small>Pedido</small><h3>#${o.id}</h3></div><span class="status">${o.status}</span></div>${o.status==='Cancelado'?'<div class="cancelBox">❌ Pedido cancelado</div>':o.payment==='Pix'&&!o.paid?'<div class="paymentBox">🔷 Aguardando confirmação do pagamento Pix</div>':'<div class="timeline">'+steps.map((s,i)=>`<div class="step ${i<=p?'done':''}"><span>${i<=p?'✓':i+1}</span><b>${s}</b></div>`).join('')+'</div>'}<div class="trackInfo"><p><b>Itens:</b> ${o.items}</p><p><b>Total:</b> ${brl(o.total)}</p><p><b>Pagamento:</b> ${o.payment}${o.paid?' · Pago':''}</p><p><b>Modalidade:</b> ${o.delivery}</p><p><b>📍 Local:</b> ${o.address?o.address.rua+', '+o.address.numero+' — '+o.address.bairro:'Retirada no local'}</p></div>`}
function trackOrder(){const id=$('trackId').value.trim(),ph=$('trackPhone').value.replace(/\D/g,''),o=orders.find(x=>String(x.id)===id&&String(x.phone||'').replace(/\D/g,'')===ph);if(!o)return toast('Pedido não encontrado.');localStorage.bv_last_order=JSON.stringify({id:o.id,phone:o.phone});renderTracking(o)}function trackLastOrder(){const l=safeParse('bv_last_order',null);if(!l)return toast('Ainda não há pedido.');$('trackId').value=l.id;$('trackPhone').value=l.phone||'';trackOrder()}
function renderManage(){if(!$('manage'))return;if($('productCount'))$('productCount').textContent=products.length+' produto'+(products.length===1?'':'s');$('manage').innerHTML=products.map((p,i)=>`<div class="manageProduct"><div class="manageProductInfo"><div class="manageEmoji">${p.emoji||'🍔'}</div><div><span class="categoryBadge">${p.category||'Lanches'}</span><h3>${String(p.name).replace(/</g,'&lt;')}</h3><strong>${brl(p.price)}</strong><p>${String(p.desc||'Sem descrição').replace(/</g,'&lt;')}</p></div></div><button class="deleteProduct" onclick="removeProduct(${i})">Excluir</button></div>`).join('')}
function openProductForm(){const b=$('productFormPanel');if(!b)return;b.classList.add('show');$('productName')?.focus()}function closeProductForm(){const b=$('productFormPanel');if(b)b.classList.remove('show')}
function addProduct(e){if(e)e.preventDefault();const n=$('productName').value.trim(),v=parseFloat($('productPrice').value),c=$('productCategory').value,d=$('productDesc').value.trim();if(!n)return toast('Informe o nome do produto.');if(isNaN(v)||v<0)return toast('Informe um valor válido.');if(!d)return toast('Informe a descrição.');products.push({id:Date.now(),name:n,price:v,emoji:c==='Bebidas'?'🥤':'🍔',desc:d,category:c});localStorage.bv_products=JSON.stringify(products);$('productName').value='';$('productPrice').value='';$('productCategory').value='Lanches';$('productDesc').value='';closeProductForm();renderProducts();toast('Produto cadastrado com sucesso!')}
function removeProduct(i){if(confirm('Excluir este produto?')){products.splice(i,1);localStorage.bv_products=JSON.stringify(products);renderProducts();toast('Produto excluído.')}}
function renderUsers(){if(!admin())return;const all=users(),box=$('userPermissions');if(!box)return;const q=String($('userSearch')?.value||'').trim().toLowerCase();const list=q?all.filter(u=>String(u.name||'').toLowerCase().includes(q)||String(u.email||'').toLowerCase().includes(q)):all;if($('userCount'))$('userCount').textContent=all.length+' usuário'+(all.length===1?'':'s');if(!list.length){box.innerHTML='<div class="emptyUsers"><b>Nenhum usuário encontrado.</b><small>Os usuários cadastrados aparecerão aqui.</small></div>';return}box.innerHTML=list.map((u,i)=>{const role=u.role==='administrador'?'🔐 Administrador':u.role==='motoboy'?'🏍️ Motoboy':'👤 Usuário';return `<div class="userPerm"><div class="userIndex">${i+1}</div><div class="userIdentity"><b>${String(u.name||'Sem nome').replace(/</g,'&lt;')}</b><small>${String(u.email||'').replace(/</g,'&lt;')}</small><em>${role}</em></div><select onchange="changeUserRole('${String(u.id||'').replace(/'/g,"\\'")}',this.value)" ${u.id==='admin-marco'?'disabled':''}><option value="usuario" ${u.role==='usuario'?'selected':''}>👤 Usuário</option><option value="motoboy" ${u.role==='motoboy'?'selected':''}>🏍️ Motoboy</option><option value="administrador" ${u.role==='administrador'?'selected':''}>🔐 Administrador</option></select></div>`}).join('')}
function createUser(){if(!admin())return toast('Somente o administrador pode cadastrar usuários.');const name=$('newUserName')?.value.trim()||'',email=$('newUserEmail')?.value.trim().toLowerCase()||'',pass=$('newUserPass')?.value||'';if(!name||!email||!pass)return toast('Preencha nome, e-mail e senha.');const list=users();if(list.some(u=>u.email.toLowerCase()===email))return toast('Este e-mail já está cadastrado.');list.push({id:'user-'+Date.now(),name,email,pass,role:'usuario'});localStorage.bv_users=JSON.stringify(list);$('newUserName').value='';$('newUserEmail').value='';$('newUserPass').value='';renderUsers();toast('Usuário cadastrado como usuário comum.')}
function changeUserRole(id,newRole){if(!admin())return toast('Somente o administrador pode alterar permissões.');if(id==='admin-marco')return toast('O administrador principal não pode perder o acesso.');if(!['usuario','motoboy','administrador'].includes(newRole))return;const list=users(),u=list.find(x=>x.id===id);if(!u)return;u.role=newRole;localStorage.bv_users=JSON.stringify(list);renderUsers();toast('Permissão atualizada.')}
function addBairroFee(){const n=$('bairroCfg')?.value.trim().toLowerCase(),v=parseFloat($('bairroFeeCfg')?.value);if(!n||isNaN(v)||v<0)return toast('Informe bairro e taxa.');config.bairroFees[n]=v;localStorage.bv_config=JSON.stringify(config);$('bairroCfg').value='';$('bairroFeeCfg').value='';renderBairroFees();toast('Bairro cadastrado.')}
function renderBairroFees(){const b=$('bairroFees');if(!b)return;b.innerHTML=Object.entries(config.bairroFees||{}).map(([n,v])=>`<div class="line"><span>${n}</span><b>${brl(v)}</b></div>`).join('')||'<p class="muted">Nenhum bairro cadastrado.</p>'}
function saveCfg(){config.fee=parseFloat($('feeCfg')?.value)||0;config.wa=$('waCfg')?.value||config.wa;localStorage.bv_config=JSON.stringify(config);toast('Configurações salvas.')}
function demoOrder(){const o={id:String(Date.now()).slice(-5),customer:'Cliente teste',phone:'31999999999',items:'1x X-Salada',total:12.99,payment:'Pix',delivery:'Entrega',address:{rua:'Rua Teste',numero:'10',bairro:'Centro'},status:'Aguardando pagamento',paid:false,time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})};orders.unshift(o);localStorage.bv_orders=JSON.stringify(orders);renderAdmin();toast('Pedido simulado.')}
function init(){applyAccess();const r=role();if(r)showPage(r==='administrador'?'dashboard':r==='motoboy'?'pedidos':'inicio');else showPage('inicio');if(saved){if($('name'))$('name').value=saved.name||'';if($('phone'))$('phone').value=saved.phone||'';if($('street'))$('street').value=saved.rua||'';if($('num'))$('num').value=saved.numero||'';if($('bairro'))$('bairro').value=saved.bairro||'';if($('cep'))$('cep').value=saved.cep||'';if($('comp'))$('comp').value=saved.complemento||''}}
window.addEventListener('load',()=>{init();$('email')?.addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('pass')?.addEventListener('keydown',e=>{if(e.key==='Enter')login()})});